[workspace]
members = ["bin/wealth_watcher", "crates/adapters", "crates/domain"]

default-members = ["bin/wealth_watcher"]

[workspace.dependencies]
## eth
ethers = "2.0"
ethers-signers = "2.0"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
